### ISSUE TITLE
请教部署方法

### ISSUE THREAD

**Issue by Spider-DT** [KevinWang15/breeze#1]
### 你好，Kevin
一直在寻找合适的工具，来记录网页阅读笔记
比如在这样的纯文本HTML中：http://www.guoxue123.com/shibu/0101/00hhsz/033.htm
---
想请教下：
1. 具体该如何实现呢？（安装插件？）
2. 作为网页的运营者，又该如何将高亮功能集成到网页，方便读者直接使用呢？类似 Medium.com

**Comment by KevinWang15** [comment]
Hi, @Spider-DT  这个项目我现在不做了，改名为：https://github.com/notelix/notelix
你可以关注一下这个新项目，breeze有的功能都迁移到这个新项目了
新项目有个Chrome插件，你可以根据说明安装、尝试
要集成到自己的网页，需要一些开发。技术上最难的部分是网页高亮，我做成了一个独立的组件 https://github.com/notelix/web-marker MIT协议可以直接用。在此基础上，做一些高亮按钮、后端接口等，就可以集成到自己网页了。 notelix这些都实现了，但是notelix是浏览器插件，设计初衷不是一个可以被安装到网站上的功能。尽管如此，它们代码有很多类似的，可以参考。

**Comment by Spider-DT** [comment]
感谢回复 @KevinWang15 ，或许我可以参与到 https://github.com/notelix/notelix 中，
插件高亮和评论的内容是写到Mysql 中的吗？
如果是的话，后续做标签分析，就能抵半个Diigo了  :)

**Comment by KevinWang15** [comment]
是的，目前是用Nest.js做后端，数据库是MySQL，我就是想做一个开源、可以自己部署的weava/diigo
实际上我现在每天都自己用notelix插件，体验还是可以的（至少在高亮准确度方面和weava/diigo是一个等级）
的确还缺不少功能，比如一个管理划线、搜索笔记的后台等等
这个项目有一些roadmap，我也愿意继续做下去，只是业余时间比较少
有兴趣的话欢迎加入

**Comment by KevinWang15** [comment]
@Spider-DT 可以试试这个，我刚刚做了一个SaaS模式，接入很简单 https://github.com/notelix/notelix/blob/master/chrome-extension/saas.html

**Comment by Spider-DT** [comment]
多谢提醒，最近太忙了，一直没得空
我来试试


| |
王鹏
|
|
***@***.***
|
在2022年3月5日 16:51，Ke ***@***.***> 写道：

@Spider-DT 可以试试这个，我刚刚做了一个SaaS模式，接入很简单 https://github.com/notelix/notelix/blob/master/chrome-extension/saas.html

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
